name: mymusic
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #路由框架
  fluro:
    git: git://github.com/theyakka/fluro.git
  #add flutter_screenutil
  flutter_screenutil: ^2.1.0
  #add webview_flutter
  webview_flutter: 0.3.19+9
  #add fluttertoast
  fluttertoast: ^4.0.1
  #add url_launcher
  url_launcher: ^5.4.11
  #add dio
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  #shared_preferences
  shared_preferences: ^0.5.7+3
  #path_provider
  path_provider: ^1.6.11
  #permission_handler
  permission_handler: ^5.0.1+1
  #provider
  provider: ^4.1.3
  #flutter_swiper
  flutter_swiper : ^1.1.6
  #pull_to_refresh
  pull_to_refresh: ^1.6.0
  #cached_network_image
  cached_network_image: ^2.2.0+1
  #flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.3.0
  #video_player
  video_player: ^0.10.11+2
  #video_player
  chewie: ^0.9.10
  #audioplayers
  audioplayers: ^0.15.1
  #add sqflite
  sqflite: ^1.3.1
  #add marquee
  marquee: ^1.5.2
  #add flutter_local_notifications
  flutter_local_notifications: 1.4.2
  #add flutter_widgets
  flutter_widgets: 0.1.12
  gzx_dropdown_menu: ^2.1.0
  share: ^0.6.4+3
  image_picker: ^0.6.7+3
  flutter_downloader: ^1.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  # assets-generator-begin
  # assets/img/*
    - assets/img/icon_login.png
    - assets/img/ic_about_us.png
    - assets/img/ic_add_img.png
    - assets/img/ic_album.png
    - assets/img/ic_arrow_r.png
    - assets/img/ic_arrow_red_play.png
    - assets/img/ic_banner_default.jpg
    - assets/img/ic_bottom_add.png
    - assets/img/ic_bottom_controller.png
    - assets/img/ic_bottom_del.png
    - assets/img/ic_bottom_play.png
    - assets/img/ic_clouddriver.png
    - assets/img/ic_collect.png
    - assets/img/ic_collect_all.png
    - assets/img/ic_comment.png
    - assets/img/ic_comment_black.png
    - assets/img/ic_daily_recommend.png
    - assets/img/ic_del_img.png
    - assets/img/ic_dj_cat.png
    - assets/img/ic_dj_rank.png
    - assets/img/ic_download.png
    - assets/img/ic_download_black.png
    - assets/img/ic_download_manager.png
    - assets/img/ic_dragonball_icn_daily.png
    - assets/img/ic_dragonball_icn_look.png
    - assets/img/ic_dragonball_icn_playlist.png
    - assets/img/ic_dragonball_icn_radio.png
    - assets/img/ic_dragonball_icn_rank.png
    - assets/img/ic_drawer_vip_bg.png
    - assets/img/ic_drawer_vip_fo.png
    - assets/img/ic_exit.png
    - assets/img/ic_friend.png
    - assets/img/ic_head_default.png
    - assets/img/ic_hotsong_play.png
    - assets/img/ic_jd_pay_hq.png
    - assets/img/ic_kt_vip_bg.png
    - assets/img/ic_kt_vip_text.png
    - assets/img/ic_like_song.png
    - assets/img/ic_list_play.png
    - assets/img/ic_live.png
    - assets/img/ic_local_music.png
    - assets/img/ic_login_email.png
    - assets/img/ic_login_qq.png
    - assets/img/ic_login_wb.png
    - assets/img/ic_login_wx.png
    - assets/img/ic_love_music.png
    - assets/img/ic_lrc_play.png
    - assets/img/ic_magnetic.png
    - assets/img/ic_menu_add.png
    - assets/img/ic_menu_cl.png
    - assets/img/ic_menu_create.png
    - assets/img/ic_menu_day.png
    - assets/img/ic_menu_dd.png
    - assets/img/ic_menu_del.png
    - assets/img/ic_menu_ds.png
    - assets/img/ic_menu_edit.png
    - assets/img/ic_menu_game.png
    - assets/img/ic_menu_logout.png
    - assets/img/ic_menu_ls.png
    - assets/img/ic_menu_nearby.png
    - assets/img/ic_menu_night.png
    - assets/img/ic_menu_orderby.png
    - assets/img/ic_menu_setting.png
    - assets/img/ic_menu_shop.png
    - assets/img/ic_menu_t.png
    - assets/img/ic_menu_wifi.png
    - assets/img/ic_mine_fm.png
    - assets/img/ic_msg.png
    - assets/img/ic_multiselect.png
    - assets/img/ic_mul_select.png
    - assets/img/ic_music.png
    - assets/img/ic_my_collection.png
    - assets/img/ic_my_friend.png
    - assets/img/ic_my_message.png
    - assets/img/ic_my_radio.png
    - assets/img/ic_my_sub.png
    - assets/img/ic_my_top_bg.png
    - assets/img/ic_nearby.png
    - assets/img/ic_new_song.png
    - assets/img/ic_nextplay.png
    - assets/img/ic_night_mode.png
    - assets/img/ic_personal_fm.png
    - assets/img/ic_person_home.png
    - assets/img/ic_per_dress.png
    - assets/img/ic_playall.png
    - assets/img/ic_playaudio_black.png
    - assets/img/ic_playcount.png
    - assets/img/ic_playlist.png
    - assets/img/ic_play_delete.png
    - assets/img/ic_play_flag.png
    - assets/img/ic_play_list.png
    - assets/img/ic_play_live.png
    - assets/img/ic_play_next.png
    - assets/img/ic_play_pause.png
    - assets/img/ic_play_start.png
    - assets/img/ic_radio.png
    - assets/img/ic_random_play.png
    - assets/img/ic_rank.png
    - assets/img/ic_ranking.png
    - assets/img/ic_recent_play.png
    - assets/img/ic_rubish_bin.png
    - assets/img/ic_search_singer.png
    - assets/img/ic_setting.png
    - assets/img/ic_share.png
    - assets/img/ic_share_black.png
    - assets/img/ic_share_dd.png
    - assets/img/ic_share_friend.png
    - assets/img/ic_share_link.png
    - assets/img/ic_share_music.png
    - assets/img/ic_share_qq.png
    - assets/img/ic_share_qqzone.png
    - assets/img/ic_share_sms.png
    - assets/img/ic_share_wb.png
    - assets/img/ic_share_wx.png
    - assets/img/ic_sheet_dl.png
    - assets/img/ic_sheet_import.png
    - assets/img/ic_sheet_manager.png
    - assets/img/ic_sheet_recovery.png
    - assets/img/ic_singer.png
    - assets/img/ic_single_play.png
    - assets/img/ic_songinfo.png
    - assets/img/ic_song_friend.png
    - assets/img/ic_song_sc.png
    - assets/img/ic_sp_comment.png
    - assets/img/ic_sp_comment_l.png
    - assets/img/ic_sp_download.png
    - assets/img/ic_sp_like.png
    - assets/img/ic_sp_list.png
    - assets/img/ic_sp_more.png
    - assets/img/ic_sp_no_comment.png
    - assets/img/ic_sp_pause.png
    - assets/img/ic_sp_play.png
    - assets/img/ic_sp_playlist.png
    - assets/img/ic_sp_play_next.png
    - assets/img/ic_sp_previous.png
    - assets/img/ic_sp_random.png
    - assets/img/ic_sp_ring.png
    - assets/img/ic_sp_single.png
    - assets/img/ic_sp_un_like.png
    - assets/img/ic_theme.png
    - assets/img/ic_thumbs.png
    - assets/img/ic_tie.png
    - assets/img/ic_video_play.png
    - assets/img/ic_vinyl_records_bg.png
    - assets/img/ic_watch_view.png
    - assets/img/iv_back.png
    - assets/img/iv_mi.png
    - assets/img/loading.png
    - assets/img/splash_view.png
    - assets/img/t_actionbar_video_selected.png
  # assets-generator-end
  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
